### ISSUE TITLE
Add workshops / events related to modV

### ISSUE THREAD

**Issue by TimPietrusky** [vcync/modv.vcync.gl#19]
It would be nice if we would post the upcoming workshops on the page so that people can participate. And if there are no workshops, we could refer to the https://visualandlightworkshop.com page so that people can register for updates.

Where should this be added? I think the homepage would be good (having a section "Workshops" or "Events") and then a separate page that lists all of the workshops / events. 

@2xAA what do you think?

**Comment by 2xAA** [comment]
@TimPietrusky Yes, this sounds good.

Vuepress supports custom Vue components, so maybe we should add a component which reads a list of upcoming workshops and displays them in date order so we don't have to manually update the order every time?

If there are no upcoming workshops it will automatically show the VALW link so people can register interest.
